[project]
name = "lgflow"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "marimo>=0.17.0",
]

[tool.marimo.runtime]
dotenv = [".env", ".env.testing"]
